### ISSUE TITLE
deploy.prototxt ?

### ISSUE THREAD

**Issue by segalinc** [TebogoNakampe/XRDrive-Sim#1]
Where is located or can be downloaded deploy.prototxt?

**Comment by TebogoNakampe** [comment]
Hi @cristinasegalin Sorry for the delayed response.

XRDrive Sim uses MxNet hence there is no deploy.prototxt from Caffe. 
If you are referring to openpose (https://github.com/TebogoNakampe/XRDriveSim/blob/master/openpose.py) and Resnet Face (https://github.com/TebogoNakampe/XRDriveSim/blob/master/resnet_ssd_face_python.py), implementation using Intel OpenVINO and RealSense D400 series, the deploy.prototxt were obtained from opencv_extra : https://github.com/opencv/opencv_extra/tree/master/testdata/dnn 

Hope it helps!!!

**Comment by TechTouchABI** [comment]
I guess it worked, but feel free to reopen the issue. Thanks.
